insert into product (name, desc, vendor_id, category_id, price) values ('Sandwich Wrap', 'Customizable intangible open architecture', '3', '3', '4');
insert into product (name, desc, vendor_id, category_id, price) values ('Energy Drink Red Bull', 'Fully-configurable real-time monitoring', '1', '2', '9');
insert into product (name, desc, vendor_id, category_id, price) values ('Pasta - Tortellini, Fresh', 'Pre-emptive contextually-based software', '6', '1', '9');
insert into product (name, desc, vendor_id, category_id, price) values ('Ginsing - Fresh', 'Proactive systematic structure', '4', '0', '7');
insert into product (name, desc, vendor_id, category_id, price) values ('Food Colouring - Orange', 'Virtual modular ability', '3', '7', '7');
insert into product (name, desc, vendor_id, category_id, price) values ('Sauce - Sesame Thai Dressing', 'Organized zero defect conglomeration', '6', '3', '8');
insert into product (name, desc, vendor_id, category_id, price) values ('Maple Syrup', 'Polarised human-resource capacity', '7', '2', '6');
insert into product (name, desc, vendor_id, category_id, price) values ('Beef - Baby, Liver', 'Multi-tiered didactic groupware', '2', '8', '3');
insert into product (name, desc, vendor_id, category_id, price) values ('Pork - Loin, Boneless', 'Switchable bifurcated pricing structure', '8', '6', '6');
insert into product (name, desc, vendor_id, category_id, price) values ('Stock - Beef, Brown', 'Visionary full-range data-warehouse', '2', '4', '9');
insert into product (name, desc, vendor_id, category_id, price) values ('Bouillion - Fish', 'Intuitive impactful extranet', '3', '3', '9');
insert into product (name, desc, vendor_id, category_id, price) values ('Sobe - Cranberry Grapefruit', 'Enterprise-wide encompassing structure', '3', '5', '2');
insert into product (name, desc, vendor_id, category_id, price) values ('Sage Derby', 'Sharable optimal archive', '5', '6', '5');
insert into product (name, desc, vendor_id, category_id, price) values ('Shrimp - Black Tiger 8 - 12', 'Front-line user-facing structure', '4', '2', '4');
insert into product (name, desc, vendor_id, category_id, price) values ('Syrup - Chocolate', 'Seamless client-server local area network', '3', '9', '3');
insert into product (name, desc, vendor_id, category_id, price) values ('Piping Jelly - All Colours', 'User-centric context-sensitive parallelism', '1', '8', '5');
insert into product (name, desc, vendor_id, category_id, price) values ('Flax Seed', 'Devolved well-modulated system engine', '4', '5', '9');
insert into product (name, desc, vendor_id, category_id, price) values ('Chocolate Bar - Reese Pieces', 'Self-enabling regional data-warehouse', '6', '7', '7');
insert into product (name, desc, vendor_id, category_id, price) values ('Muffin Mix - Oatmeal', 'Digitized tangible middleware', '6', '2', '6');
insert into product (name, desc, vendor_id, category_id, price) values ('Quail - Whole, Bone - In', 'Synchronised mission-critical leverage', '6', '9', '2');
insert into product (name, desc, vendor_id, category_id, price) values ('Ice Cream Bar - Oreo Sandwich', 'Multi-layered optimizing intranet', '7', '4', '7');
insert into product (name, desc, vendor_id, category_id, price) values ('Wine - White, Mosel Gold', 'Focused uniform projection', '0', '4', '9');
insert into product (name, desc, vendor_id, category_id, price) values ('Bread - Roll, Calabrese', 'Ameliorated motivating analyzer', '1', '5', '9');
insert into product (name, desc, vendor_id, category_id, price) values ('Almonds Ground Blanched', 'Phased hybrid contingency', '1', '2', '5');
insert into product (name, desc, vendor_id, category_id, price) values ('V8 Pet', 'Re-engineered user-facing open architecture', '4', '2', '7');