insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Black Digital Watch', 'Green Display', '1', '1', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Grey Digital Watch', 'White Display', '1', '1', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Pink Digital Watch', 'Yellow Display', '1', '1', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Black Analog Watch', 'Brown Band', '2', '1', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Gold Analog Watch', 'Blue Band', '2', '1', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Grey Analog Watch', 'Black Band', '2', '1', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Fujinon Mirrorless Camera', 'Silver Lens', '3', '2', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Lumix Mirrorless Camera', 'Black Lens', '3', '2', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Canon Mirrorless Camera', 'Grey Lens', '3', '2', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Canon DSLR Camera', 'Canon Lens', '4', '2', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Sony DSLR Camera', 'Sony Lens', '4', '2', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Pentax DSLR Camera', 'Pentax Lens', '4', '2', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Vivo Mobile Phone', 'Vivo Screen', '5', '3', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Samsung Mobile Phone', 'Samsung Screen', '5', '3', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Apple Mobile Phone', 'Apple Screen', '5', '3', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('BT Desk Phone', 'BT Screen', '6', '3', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Panasonic Desk Phone', 'Panasonic Screen', '6', '3', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Motorola Desk Phone', 'Motorola Screen', '6', '3', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Samsung Business Laptop', 'Samsung Screen', '7', '4', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('TravelTrust Business Laptop', 'TravelTrust Screen', '7', '4', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Asus Business Laptop', 'Asus Screen', '7', '4', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Asus Gaming Laptop', 'Asus Screen', '8', '4', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Lenovo Gaming Laptop', 'Lenovo Screen', '8', '4', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Razer Gaming Laptop', 'Razer Screen', '8', '4', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Smart Bullet Blender', 'Smart Base', '9', '5', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Nutri Bullet Blender', 'Nutri Base', '9', '5', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Magic Bullet Blender', 'Magic Base', '9', '5', '3', '5', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Bar Cocktail Blender', 'Bar Base', '10', '5', '1', '3', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Breville Round Cocktail Blender', 'Breville Round Base', '10', '5', '2', '4', true);
insert into product (name, desc, vendor_id, category_id, price, rating, enabled) values ('Breville Square Cocktail Blender', 'Breville Square Base', '10', '5', '3', '5', true);
insert into product_image (product_id, image_url) values (1, '1.png');
insert into product_image (product_id, image_url) values (2, '1.png');
insert into product_image (product_id, image_url) values (3, '1.png');
insert into product_image (product_id, image_url) values (4, '1.png');
insert into product_image (product_id, image_url) values (5, '1.png');
insert into product_image (product_id, image_url) values (6, '1.png');
insert into product_image (product_id, image_url) values (7, '1.png');
insert into product_image (product_id, image_url) values (8, '1.png');
insert into product_image (product_id, image_url) values (9, '1.png');
insert into product_image (product_id, image_url) values (10, '1.png');
insert into product_image (product_id, image_url) values (11, '1.png');
insert into product_image (product_id, image_url) values (12, '1.png');
insert into product_image (product_id, image_url) values (13, '1.png');
insert into product_image (product_id, image_url) values (14, '1.png');
insert into product_image (product_id, image_url) values (15, '1.png');
insert into product_image (product_id, image_url) values (16, '1.png');
insert into product_image (product_id, image_url) values (17, '1.png');
insert into product_image (product_id, image_url) values (18, '1.png');
insert into product_image (product_id, image_url) values (19, '1.png');
insert into product_image (product_id, image_url) values (20, '1.png');
insert into product_image (product_id, image_url) values (21, '1.png');
insert into product_image (product_id, image_url) values (22, '1.png');
insert into product_image (product_id, image_url) values (23, '1.png');
insert into product_image (product_id, image_url) values (24, '1.png');
insert into product_image (product_id, image_url) values (25, '1.png');
insert into product_image (product_id, image_url) values (26, '1.png');
insert into product_image (product_id, image_url) values (27, '1.png');
insert into product_image (product_id, image_url) values (28, '1.png');
insert into product_image (product_id, image_url) values (29, '1.png');
insert into product_image (product_id, image_url) values (30, '1.png');