insert into category (name, description, enabled) values ('Foam Dinner Plate', 'Operative regional complexity', true);
insert into category (name, description, enabled) values ('Ecolab Silver Fusion', 'Grass-roots encompassing challenge', true);
insert into category (name, description, enabled) values ('Lamb - Shoulder', 'Expanded national middleware', true);
insert into category (name, description, enabled) values ('Vinegar - White', 'Open-source leading edge structure', true);
insert into category (name, description, enabled) values ('Energy Drink Red Bull', 'Object-based hybrid data-warehouse', true);
insert into category (name, description, enabled) values ('Soy Protein', 'Integrated global knowledge user', true);
insert into category (name, description, enabled) values ('Fond - Chocolate', 'Right-sized intangible Graphic Interface', true);
insert into category (name, description, enabled) values ('Water - Evian 355 Ml', 'Up-sized non-volatile project', true);
insert into category (name, description, enabled) values ('Nut - Pecan, Halves', 'Configurable 3rd generation open system', true);
insert into category (name, description, enabled) values ('Bread - 10 Grain Parisian', 'Public-key static migration', true);
insert into category (name, description, enabled) values ('Pasta - Fettuccine, Egg, Fresh', 'Expanded 3rd generation frame', true);
insert into category (name, description, enabled) values ('Star Anise, Whole', 'Triple-buffered directional open architecture', true);
insert into category (name, description, enabled) values ('Juice - Orange', 'Proactive context-sensitive migration', true);
insert into category (name, description, enabled) values ('Eel - Smoked', 'Adaptive coherent application', true);
insert into category (name, description, enabled) values ('Lobster - Tail 6 Oz', 'Expanded systemic process improvement', true);
insert into category (name, description, enabled) values ('Tea Leaves - Oolong', 'Down-sized optimizing product', true);
insert into category (name, description, enabled) values ('Lychee', 'Compatible responsive infrastructure', true);
insert into category (name, description, enabled) values ('Lamb - Ground', 'Synergized disintermediate utilisation', true);
insert into category (name, description, enabled) values ('Veal - Shank, Pieces', 'Organic even-keeled array', true);
insert into category (name, description, enabled) values ('Skirt - 24 Foot', 'Face to face 24 hour superstructure', true);
insert into category (name, description, enabled) values ('Muffin Puck Ww Carrot', 'Grass-roots exuding synergy', true);
insert into category (name, description, enabled) values ('Kellogs Raisan Bran Bars', 'Advanced demand-driven encryption', true);
insert into category (name, description, enabled) values ('Bread - White Mini Epi', 'Total multi-tasking database', true);
insert into category (name, description, enabled) values ('Muffin Puck Ww Carrot', 'Open-source didactic adapter', true);
insert into category (name, description, enabled) values ('Potatoes - Yukon Gold, 80 Ct', 'Synergistic full-range initiative', true);