insert into category (name, description ) values ('Foam Dinner Plate', 'Operative regional complexity');
insert into category (name, description ) values ('Ecolab Silver Fusion', 'Grass-roots encompassing challenge');
insert into category (name, description ) values ('Lamb - Shoulder', 'Expanded national middleware');
insert into category (name, description ) values ('Vinegar - White', 'Open-source leading edge structure');
insert into category (name, description ) values ('Energy Drink Red Bull', 'Object-based hybrid data-warehouse');
insert into category (name, description ) values ('Soy Protein', 'Integrated global knowledge user');
insert into category (name, description ) values ('Fond - Chocolate', 'Right-sized intangible Graphic Interface');
insert into category (name, description ) values ('Water - Evian 355 Ml', 'Up-sized non-volatile project');
insert into category (name, description ) values ('Nut - Pecan, Halves', 'Configurable 3rd generation open system');
insert into category (name, description ) values ('Bread - 10 Grain Parisian', 'Public-key static migration');
insert into category (name, description ) values ('Pasta - Fettuccine, Egg, Fresh', 'Expanded 3rd generation frame');
insert into category (name, description ) values ('Star Anise, Whole', 'Triple-buffered directional open architecture');
insert into category (name, description ) values ('Juice - Orange', 'Proactive context-sensitive migration');
insert into category (name, description ) values ('Eel - Smoked', 'Adaptive coherent application');
insert into category (name, description ) values ('Lobster - Tail 6 Oz', 'Expanded systemic process improvement');
insert into category (name, description ) values ('Tea Leaves - Oolong', 'Down-sized optimizing product');
insert into category (name, description ) values ('Lychee', 'Compatible responsive infrastructure');
insert into category (name, description ) values ('Lamb - Ground', 'Synergized disintermediate utilisation');
insert into category (name, description ) values ('Veal - Shank, Pieces', 'Organic even-keeled array');
insert into category (name, description ) values ('Skirt - 24 Foot', 'Face to face 24 hour superstructure');
insert into category (name, description ) values ('Muffin Puck Ww Carrot', 'Grass-roots exuding synergy');
insert into category (name, description ) values ('Kellogs Raisan Bran Bars', 'Advanced demand-driven encryption');
insert into category (name, description ) values ('Bread - White Mini Epi', 'Total multi-tasking database');
insert into category (name, description ) values ('Muffin Puck Ww Carrot', 'Open-source didactic adapter');
insert into category (name, description ) values ('Potatoes - Yukon Gold, 80 Ct', 'Synergistic full-range initiative');